name: Generate Countries & Flags

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'npm'

      - name: Install dependencies
        run: npm i node-fetch

      - name: Generate countries.js + flags
        run: node generate.js

      - name: Package
        run: |
          zip -r countries-flags.zip countries.js flags

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: countries-flags-16x12
          path: countries-flags.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: countries-flags.zip
